-- Community highlights — shared, read-only annotations visible to all users.

CREATE TABLE IF NOT EXISTS public_highlights (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     text NOT NULL,
  text_uid    text NOT NULL,
  start_offset int NOT NULL,
  end_offset  int NOT NULL,
  colour      text NOT NULL DEFAULT '#FFD700',
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, text_uid, start_offset, end_offset)
);

-- RLS: anyone authenticated can read, users can only write their own
ALTER TABLE public_highlights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view community highlights"
  ON public_highlights FOR SELECT
  USING (true);

CREATE POLICY "Users can insert own community highlights"
  ON public_highlights FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can delete own community highlights"
  ON public_highlights FOR DELETE
  USING (auth.uid()::text = user_id);
